name: Output event details on issues
on: [issues, workflow_dispatch]
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "Issue opened by ${{ github.actor }} on ${{ github.repository }} at ${{ github.event.issue.created_at }}." 
          echo "Issue ${{ toJSON(github.event.issue) }}Issue title: ${{ github.event.issue.title }} and Issue body: ${{ github.event.issue.body }}"
        