name: Output event details on issues
on: issues
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "Issue opened by ${{ github.actor }} on ${{ github.repository }} at ${{ github.event.issue.created_at }}"